name: "analytics"
require-dbt-version: [">=1.0.0", "<2.0.0"]
version: "1.0.0"

profile: "analytics"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  analytics:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
